### ISSUE TITLE
NGINX failed

### ISSUE THREAD

**Issue by devkdas** [tiandrey/nginx-sslkeylog#1]
Hi @tiandrey ,

Nginx process failed after, and issue is "sslkeylog_cs" in nginx.conf.

Could you please look into this

root@ubuntu:/etc/nginx# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-01-06 10:15:19 UTC; 7s ago
       Docs: man:nginx(8)
    Process: 365744 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Jan 06 10:15:19 ubuntu systemd[1]: Starting A high performance web server and a reverse proxy server...
Jan 06 10:15:19 ubuntu nginx[365744]: nginx: [emerg] unknown "sslkeylog_cs" variable
Jan 06 10:15:19 ubuntu nginx[365744]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jan 06 10:15:19 ubuntu systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Jan 06 10:15:19 ubuntu systemd[1]: nginx.service: Failed with result 'exit-code'.
Jan 06 10:15:19 ubuntu systemd[1]: Failed to start A high performance web server and a reverse proxy server.

Looking forward for your reply

Thank you,

**Comment by tiandrey** [comment]
Hello. It seems that you didn't load dynamic version of module and built nginx without statically linking the module.
Please show your nginx build info (`nginx -V`) and config.

**Comment by tiandrey** [comment]
Also please note that this module is currently http-only and does not work for streams (although it should be easy enough to copy logic for streams).

**Comment by devkdas** [comment]
Thank you for replying back.

here is the output 

root@ubuntu:/src/nginx-quic# nginx -V
nginx version: nginx/1.23.4 (nginx-quic)
built by gcc 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
built with OpenSSL 1.1.1 (compatible; BoringSSL) (running with BoringSSL)
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-compat --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module --build=nginx-quic --with-debug --with-http_v3_module --with-stream_quic_module --with-cc-opt=-I/src/boringssl/include --with-ld-opt='-L/src/boringssl/build/ssl -L/src/boringssl/build/crypto'

**Comment by devkdas** [comment]
root@ubuntu:/src/nginx-quic# cat /etc/nginx/nginx.conf
user www-data;
worker_processes auto;
pid /run/nginx.pid;
#include /etc/nginx/modules-enabled/*.conf;

events {
           worker_connections 768;
          # multi_accept on;
}

http {

   ##
   # Basic Settings
   ##

   sendfile on;
   tcp_nopush on;
   tcp_nodelay on;
   keepalive_timeout 65;
   types_hash_max_size 2048;
   # server_tokens off;

   # server_names_hash_bucket_size 64;
   # server_name_in_redirect off;

   include /etc/nginx/mime.types;
   default_type application/octet-stream;

   ##
   # SSL Settings
   ##

   ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
   ssl_prefer_server_ciphers on;

   ##
   # Logging Settings
   ##

   access_log /var/log/nginx/access.log;
   error_log /var/log/nginx/error.log;

   ##
   # Gzip Settings
   ##

   gzip on;

   # gzip_vary on;
   # gzip_proxied any;
   # gzip_comp_level 6;
   # gzip_buffers 16 8k;
   # gzip_http_version 1.1;
   # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

   ##
   # Virtual Host Configs
   ##

   #include /etc/nginx/conf.d/*.conf;
   #include /etc/nginx/sites-enabled/*;

   ## From QUIC/HTTP3 README file
   log_format quic '$remote_addr - $remote_user [$time_local] '
                   '"$request" $status $body_bytes_sent '
                   '"$http_referer" "$http_user_agent" "$http3"';

   access_log /var/log/nginx/access.log quic;

   log_format sslkeylog '$remote_addr [$time_local] $sslkeylog_cs $sslkeylog_se $sslkeylog_cr $sslkeylog_sr $sslkeylog_mk';

   access_log  /var/log/nginx/sslkeys.log  sslkeylog;

   server {
        # for better compatibility it's recommended
        # to use the same port for quic and https
        listen 8443 http3 reuseport;
        listen 8443 ssl;

        ssl_ciphers         ALL:COMPLEMENTOFALL;
        ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
        ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
        ssl_protocols       TLSv1.1 TLSv1.2 TLSv1.3;
        #ssl_protocols       TLSv1.3;
        #ssl_ecdh_curve X25519:secp384r1;
        ssl_ecdh_curve prime256v1:secp384r1;
        #ssl_ecdh_curve      auto;
        #ssl_ecdh_curve X25519:secp384r1; to enable hrr
        ssl_session_cache   shared:SSL:10m;
        ssl_session_tickets on;
        ssl_early_data      off;


        location / {
            # required for browsers to direct them into quic port
            add_header Alt-Svc 'h3=":8443"; ma=86400';
        }
   }
}

**Comment by devkdas** [comment]
am i missing anything here

**Comment by tiandrey** [comment]
Yep, you built nginx without sslkeylog module. Please read Building section of README: https://github.com/tiandrey/nginx-sslkeylog#building

**Comment by devkdas** [comment]
i built nginx with your module,
<img width="820" alt="nginx_issue" src="https://user-images.githubusercontent.com/92445174/211022388-d01c14c9-d73f-4aa4-b88e-c935f309b2f4.PNG">

**Comment by devkdas** [comment]
not sure why it was not showing with nginx config

**Comment by devkdas** [comment]
Could you please share me how nginx config looks when your module is present in nginx config

**Comment by tiandrey** [comment]
Read output of your `nginx -V` thoroughly - there is no indication of adding sslkeylog module.
May be you forgot to `make install` after `make`?

**Comment by devkdas** [comment]
yes,missed make install and now it is working

**Comment by devkdas** [comment]
but with that ssl key lofg file unable to decrypt the QUIC traffic

**Comment by devkdas** [comment]
Thank you @tiandrey for your help.
